// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwaggerHallOfFame;

#nullable disable

namespace SwaggerHallOfFame.Migrations
{
    [DbContext(typeof(PersonDBContext))]
    [Migration("20220508141424_DBPersonSkillMigration")]
    partial class DBPersonSkillMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SwaggerHallOfFame.ConPersonSkill", b =>
                {
                    b.Property<long>("IdPersonSkill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPersonSkill"), 1L, 1);

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint");

                    b.HasKey("IdPersonSkill");

                    b.HasIndex(new[] { "PersonId" }, "IX_ConPersonSkills_PersonId");

                    b.HasIndex(new[] { "SkillId" }, "IX_ConPersonSkills_SkillId");

                    b.ToTable("ConPersonSkills");
                });

            modelBuilder.Entity("SwaggerHallOfFame.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("SwaggerHallOfFame.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("SwaggerHallOfFame.ConPersonSkill", b =>
                {
                    b.HasOne("SwaggerHallOfFame.Person", null)
                        .WithMany("ConPersonSkills")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwaggerHallOfFame.Skill", null)
                        .WithMany("ConPersonSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwaggerHallOfFame.Person", b =>
                {
                    b.Navigation("ConPersonSkills");
                });

            modelBuilder.Entity("SwaggerHallOfFame.Skill", b =>
                {
                    b.Navigation("ConPersonSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
